name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: SonarCloud Scan - Frontend
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.sources=frontend
          -Dsonar.javascript.node.maxspace=4096

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build Frontend Image
      run: |
        docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend/

    - name: Trivy Scan - Frontend Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        vuln-type: 'os,library'

    

    - name: Push Frontend Image
      run: |
        docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

    - name: Logout from Azure
      run: az logout
      if: always()